services:
  telemetry-api:
    build: .
    container_name: telemetry-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: telemetry_db
      DB_USER: telemetry_user
      DB_PASSWORD: telemetry_password

  postgres:
    image: postgres:16
    container_name: telemetry-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telemetry_db
      POSTGRES_USER: telemetry_user
      POSTGRES_PASSWORD: telemetry_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: